const express = require("express")
const noteController = require("./controller.note")
const validate = require("../../middlewares/Validation.middleware")
const {noteValidationSchema} = require("../validationSchema/notes.validation")
const authHelper = require("../../helpers/authHelper")
const router = express.Router()
  router.post("/create",authHelper, validate(noteValidationSchema),noteController.createNote)
  router.get("/getAllnote",authHelper, noteController.getAllNotes)
  router.delete("/delete/:id",authHelper ,noteController.deleteNote)
  module.exports = router